server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service
  
  config:
    import: "optional:classpath:application-secrets.yml"

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
    username: ${GLOBAL_DB_USERNAME:root}
    password: ${GLOBAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GLOBAL_GOOGLE_CLIENT_ID}
            client-secret: ${GLOBAL_GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secretkey: ${GLOBAL_JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "*"