server:
  port: 8081

spring:
  application:
    name: qma-service

  config:
    import: "optional:classpath:application-secrets.yml"

  datasource:
    url: jdbc:mysql://localhost:3306/qma_db?createDatabaseIfNotExist=true
    username: ${GLOBAL_DB_USERNAME:root}
    password: ${GLOBAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 600000

  boot:
    admin:
      client:
        url: http://localhost:9090

jwt:
  secretkey: ${GLOBAL_JWT_SECRET}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always